blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/discussions/categories/q-a
    about: Please ask and answer questions here.
  - name: Feature request
    url: https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/discussions/categories/ideas
    about: Please submit feature requests here.
